### ISSUE TITLE
Lambda node version error

### ISSUE THREAD

**Issue by dwatts418** [bwsolutions/SaaSServerless-Identity#1]
I received the following when I ran sls deploy:

"An error occurred: RegisterLambdaFunction - The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. "

**Comment by juano2310** [comment]
You can change this line to upgrade to nodejs12.x 
https://github.com/bwsolutions/SaaSServerless-Identity/blob/master/common/serverless.yml#L31

**Comment by dwatts418** [comment]
Thank you!  I got it to deploy.
